/*Copyright (c) 2015-2016 IBM Training*/

package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


public interface HrdbProcedureExecutorService {


}


